import type { ChangeEvent, Dispatch, MutableRefObject, SetStateAction } from 'react';
import type { AppTab } from '../../navigation';
import type { SchoolOrder, UdaModel, UserRole } from '../../../types/curriculum';
import type { CurriculumMap, SocialUda, ToastHandler } from './appViewContracts';

export type DetectedDeviceType = 'mobile' | 'desktop';
export type LocalAgentType = 'webgpu' | 'ollama' | 'none';
export type LocalAgentStatus = 'not_installed' | 'downloading' | 'installed';
export type LocalAgentSize = 'light' | 'full' | 'none';
export type OllamaStatus = 'idle' | 'testing' | 'connected' | 'error';
export type CloudAccountType = 'scolastica' | 'personale';

export interface AppModalsLayerProps {
  showAgentSetupModal: boolean;
  setShowAgentSetupModal: (value: boolean) => void;
  detectedDeviceType: DetectedDeviceType;
  localAgentType: LocalAgentType;
  setLocalAgentType: (value: LocalAgentType) => void;
  localAgentStatus: LocalAgentStatus;
  setLocalAgentStatus: Dispatch<SetStateAction<LocalAgentStatus>>;
  localAgentSize: LocalAgentSize;
  setLocalAgentSize: Dispatch<SetStateAction<LocalAgentSize>>;
  localAgentProgress: number;
  setLocalAgentProgress: (value: number) => void;
  activeHelpModel: string | null;
  setActiveHelpModel: (value: string | null) => void;
  ollamaServerUrl: string;
  setOllamaServerUrl: (value: string) => void;
  ollamaModelName: string;
  setOllamaModelName: (value: string) => void;
  ollamaStatus: OllamaStatus;
  setOllamaStatus: Dispatch<SetStateAction<OllamaStatus>>;
  handleTestOllamaConnection: () => void;
  checkModelRamSafety: (model: string, name: string) => boolean;
  getModelRecommendation: (model: string) => boolean;
  agentIntervalRefs: MutableRefObject<number[]>;
  showToast: ToastHandler;
  showMicPermissionGuide: boolean;
  setShowMicPermissionGuide: (value: boolean) => void;
  gemFieldActive: string | null;
  setGemFieldActive: (value: string | null) => void;
  gemSuggestedText: string;
  setGemSuggestedText: (value: string) => void;
  isGemGenerating: boolean;
  handleAcceptGemSuggestion: (text: string, editMode: boolean) => void;
  showCloudAccountModal: boolean;
  setShowCloudAccountModal: (value: boolean) => void;
  workspaceUserEmail: string;
  setWorkspaceUserEmail: (value: string) => void;
  personalUserEmail: string;
  setPersonalUserEmail: (value: string) => void;
  safeLocalStorageSetItem: (key: string, value: string) => void;
  handleWorkspaceLogin: (type: CloudAccountType) => void;
  handleLocalDriveSync: () => void;
  showOnboardingModal: boolean;
  setShowOnboardingModal: (value: boolean) => void;
  onboardingRole: UserRole;
  setOnboardingRoleLocal: (value: UserRole) => void;
  onboardingStep: number;
  setOnboardingStep: Dispatch<SetStateAction<number>>;
  onboardingOrd: SchoolOrder;
  handleSetOnboardingOrdLocal: (order: SchoolOrder) => void;
  onboardingIsSostegno: boolean;
  setOnboardingIsSostegno: (value: boolean) => void;
  onboardingDisc: string;
  setOnboardingDiscLocal: (value: string) => void;
  localCurriculum: CurriculumMap;
  onboardingCombinations: string[];
  setOnboardingCombinations: (value: string[]) => void;
  handleToggleOnboardingCombination: (combo: string) => void;
  availableSections: string[];
  setAvailableSections: (value: string[]) => void;
  newSectionInput: string;
  setNewSectionInput: (value: string) => void;
  handleAddSectionLocal: () => void;
  saveOnboardingProfile: () => void;
  getRoleLabel: (role: UserRole) => string;
  getDisciplineLabel: (discipline: string, order?: SchoolOrder) => string;
  showMottoModal: boolean;
  setShowMottoModal: (value: boolean) => void;
  selectedUda: UdaModel | null;
  setSelectedUda: (value: UdaModel | null) => void;
  handleDownloadScormManifest: (id: string) => void;
  copyUdaForRegister: (id: string) => void;
  copyUdaTextLocal: (id: string) => void;
  showOutcomesModal: boolean;
  setShowOutcomesModal: (value: boolean) => void;
  selectedUdaForOutcomes: SocialUda | null;
  selfEvaluationStars: number;
  setSelfEvaluationStars: (value: number) => void;
  outcomesAvanzato: number;
  setOutcomesAvanzato: (value: number) => void;
  outcomesIntermedio: number;
  setOutcomesIntermedio: (value: number) => void;
  outcomesBase: number;
  setOutcomesBase: (value: number) => void;
  outcomesIniziale: number;
  setOutcomesIniziale: (value: number) => void;
  criticalReflectionsInput: string;
  setCriticalReflectionsInput: (value: string) => void;
  handleSaveOutcomes: () => void;
  showSaveModal: boolean;
  setShowSaveModal: (value: boolean) => void;
  saveProgDraft: () => void;
  handleDownloadBackup: () => void;
  handleRestoreBackup: (event: ChangeEvent<HTMLInputElement>) => void;
  handleClearLocalStorageWithReset: () => void;
  isWorkspaceLoggedIn: boolean;
  workspaceClientId: string;
  setWorkspaceClientId: (value: string) => void;
  isSyncingWorkspace: boolean;
  handleWorkspaceSync: () => void;
  handleWorkspaceLogout: () => void;
  handleRestoreFromLocalEmergencyStorage: () => void;
  triggerPwaInstall: () => void;
  cloudAccountType: CloudAccountType;
  showTourModal: boolean;
  setShowTourModal: (value: boolean) => void;
  handleTabSwitch: (tab: AppTab) => void;
  generatedDocTitle: string | null;
  setGeneratedDocTitle: (value: string | null) => void;
  generatedDocText: string | null;
  setGeneratedDocText: (value: string | null) => void;
  handlePrintDocumentPdf: (title: string, text: string) => void;
  copyText: (text: string) => void | Promise<void>;
  showWikiReaderModal: boolean;
  setShowWikiReaderModal: (value: boolean) => void;
  selectedBrainDoc: string;
  getVolumeTitleWithCustom: (id: string) => string;
  getVolumePlainTxtWithCustom: (id: string) => string;
  getVolumeFullHtmlWithCustom: (id: string) => string;
  handleDeleteCustomKbDoc: (id: string) => void;
  showAddKbModal: boolean;
  setShowAddKbModal: (value: boolean) => void;
  newKbDocTitle: string;
  setNewKbDocTitle: (value: string) => void;
  newKbDocSubtitle: string;
  setNewKbDocSubtitle: (value: string) => void;
  newKbDocContent: string;
  setNewKbDocContent: (value: string) => void;
  handleAddCustomKbDoc: () => void;
}
